services:
  terraform-aws-asg-dns-discovery:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    networks:
      - local-dev-network
    command: sleep infinity
    user: root
    environment:
      # Set max line length for Black formatter
      - PYTHON_MAX_LINE_LENGTH=120
      # Create .venv in the project directory
      - POETRY_VIRTUALENVS_IN_PROJECT=true

networks:
  local-dev-network:
    external: false
